<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>MoneyTalk.Integrations.QuickBooks</RootNamespace>
    <AssemblyName>MoneyTalk.Integrations.QuickBooks</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Net.Http.Json" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MoneyTalk.Core\MoneyTalk.Core.csproj" />
  </ItemGroup>

</Project>
