namespace MoneyTalk.Core.Entities;

/// <summary>A chat thread with the Gemini-powered financial advisor.</summary>
public class AiConversation : CompanyOwnedEntity
{
    public string Title { get; set; } = "New conversation";
    public List<AiMessage> Messages { get; set; } = new();
}

public class AiMessage : EntityBase
{
    public Guid ConversationId { get; set; }
    public AiMessageRole Role { get; set; }
    public string Content { get; set; } = string.Empty;
}

/// <summary>A proactive, system-generated observation surfaced on the dashboard (e.g. "cash
/// runway is under 30 days", "3 invoices are over 60 days past due"). Distinct from chat
/// messages: these are computed locally from the ledger, not generated by Gemini, though the
/// AI assistant can elaborate on them when asked.</summary>
public class AiInsight : CompanyOwnedEntity
{
    public string Title { get; set; } = string.Empty;
    public string Detail { get; set; } = string.Empty;
    public InsightSeverity Severity { get; set; } = InsightSeverity.Info;
    public bool IsDismissed { get; set; }
}

public enum InsightSeverity
{
    Info,
    Warning,
    Critical
}
